Make sure new version number not already in use (#60)
* Update dotnet.yml

* Update changelog for release

* comment out the "if" so I can test in PR

* Test version increment in PR build

* Update dotnet.yml

remove PUSH requirement

* Update dotnet.yml

Re-enable checkout

* test increment

* Show response text

* Update dotnet.yml

* check JSON

fix counter

* syntax tweak

* drop the numbers

* Update dotnet.yml

* Update dotnet.yml

* confirm fix

* Update dotnet.yml

extra quote

* fix while syntax

* switch to maxTries pattern

* verify counter

* Update dotnet.yml

* Update dotnet.yml

extra paren

* Update dotnet.yml

* Update dotnet.yml

* Update dotnet.yml

---------

Co-authored-by: GitHub Action <action@github.com>

diff --git a/.github/workflows/dotnet.yml b/.github/workflows/dotnet.yml
--- a/.github/workflows/dotnet.yml
+++ b/.github/workflows/dotnet.yml
@@ -149,6 +149,28 @@ jobs:
             NEW_TAG="v$BASE_VERSION-pre$((PRE_VERSION + 1))"
           fi
           echo "New tag is $NEW_TAG"
+
+          echo "Let's make sure this tag doesn't already exist..."
+          tries=0
+          maxTries=5
+          while true; do
+            echo "This is try $tries"
+            RESPONSE=$(curl -sl https://api.github.com/repos/microsoft/CoseSignTool/releases/tags/$NEW_TAG)
+            if [ "$(echo "$RESPONSE" | jq -r '.message')" == "Not Found" ]; then
+              echo "Tag not found. We're good to go."
+              break
+            else
+              if [ $tries -ge $maxTries ]; then
+                echo "Max tries reached. Exiting."
+                exit 1
+              fi
+              echo "Oops! That tag already exists!"
+              NEW_TAG="${NEW_TAG%-*}-pre$(( ${NEW_TAG##*-pre} + 1 ))"   # Increment the prerelease number.
+              echo "Let's try $NEW_TAG"
+              tries=$((tries+1))
+            fi
+          done
+
           echo "::set-output name=newtag::$NEW_TAG"
         else
           echo "Invalid tag format"
